### ISSUE TITLE
Any way to debug the plugin?

### ISSUE THREAD

**Issue by farzadmf** [hlissner/zsh-autopair#28]
### What would you like to know?

Hi,

I've been using the plugin in Linux, and everything was working great. However, I recently switched to a Mac, and the auto-pair feature doesn't seem to be working, so I was wondering if there's a way to debug the behavior and see what's missing for my environment.

Thank you

**Comment by hlissner** [comment]
The only tool I'm aware of is zshdb, which I haven't personally used, but the fix for most "it doesn't work" issues is to load the plugin last (if you have other plugins installed).

In any case, this is more a general ZSH question than anything to do with this project in particular, so I'll close this. Feel free to follow up here, though.

**Comment by farzadmf** [comment]
Thank you @hlissner for your answer (a bit too late I'd say after almost 2.5 years 😮 😆 ).

I _think_ the issue I had at the time is solved (not sure honestly though). I see I have this in my `antidote` plugins as `kind:defer`; maybe that's taking care if it.

But anyway, thank you again. For someone who doesn't remember things from last week, 2.5 years is too long to remember anything 🙂
